### ISSUE TITLE
bintrayUpload does not depend on "publish${publication}PublicationToMavenLocal"

### ISSUE THREAD

**Issue by sponiro** [bintray/gradle-bintray-plugin#10]
Somehow I expected, that calling bintrayUpload, would build the artifacts it needs to upload. But it didn't. Digging a bit and I figured that the bintrayUpload task does not depend on its publications. It only depends on the pom generation task. The relevant line in the plugin: 

```
def taskName = generatePomFileFor${it[0].toUpperCase()}${it.substring(1)}Publication"
Task publishToLocalTask = project.tasks.findByName(taskName)
bintrayUpload.dependsOn(publishToLocalTask)
```

Is this a mistake? The variable name publishToLocalTask seems to support this theory.

As a workaround I did:

```
bintrayUpload {
    dependsOn "publishMavenJavaPublicationToMavenLocal"
}
```

**Comment by adriantodt** [comment]
Having the same issue.

When using Configuration-on-demand feature from Gradle, the bintrayUpload task don't have a dependency on the "publish<publication name>PublicationToMavenLocal" task.

Manually fixed it by adding the workaround that @sponiro proposed for now.

**Comment by sponiro** [comment]
This bug is now open for almost three years. I suggest documenting the workaround somewhere for people to apply if they want. This will not break existing code and still helps others.
