### ISSUE TITLE
Publish only desired flavors

### ISSUE THREAD

**Issue by HugoGresse** [bintray/gradle-bintray-plugin#100]
I'm already using this plugin that works like a charm since some months. I've recently added some `flavors` (or `productFlavors`) to my android library. But it seems that the plugin don't care about the flavor. Running `gradle tasks` output this : 

```
Publishing tasks
----------------
bintrayUpload - Publishes artifacts to bintray.com.
```

But other tasks have the flavor available in it : (flavor here are `full` and `light`)

```
Build tasks
-----------
assemble - Assembles all variants of all applications and secondary packages.
assembleAndroidTest - Assembles all the Test applications.
assembleDebug - Assembles all Debug builds.
assembleFull - Assembles all Full builds.
assembleLight - Assembles all Light builds.
```

Do you have an idea how to specify the flavor to be uploaded?

**Comment by HugoGresse** [comment]
any update on this?

**Comment by LouisCAD** [comment]
@HugoGresse I replied to the stackoverflow issue here: http://stackoverflow.com/a/41896400/4433326
Maybe such an example should be added to the bintray gradle plugin examples repository?

**Comment by rfreitas** [comment]
@HugoGresse 

try to see if this helps:

```
defaultPublishConfig 'release' //expects a release variant

// Fix for defaultPublishConfig not working as expected
// ref: https://github.com/dcendents/android-maven-gradle-plugin/issues/11
libraryVariants.all { variant ->
  if( publishNonDefault && variant.name == defaultPublishConfig ) {
    def bundleTask = tasks["bundle${variant.name.capitalize()}"]
    artifacts {
      archives(bundleTask.archivePath) {
        classifier null //necessary to get rid of the suffix in the artifact
        builtBy bundleTask
        name name.replace('-' + variant.name, '')//necessary to get rid of the suffix from the folder name
      }
    }
  }
}
```

**Comment by HugoGresse** [comment]
I think @LouisCAD solution is ok for me and was able to publish only desired flavor (plus it gave me control on the pom file). I've not used it has a final publish script though.
