### ISSUE TITLE
Could not find method publishing() for arguments

### ISSUE THREAD

**Issue by benmarten** [bintray/gradle-bintray-plugin#110]
I am running into this error which I cannot seem to resolve:

	$ gradle bintrayUpload                                                                                                                                      
	FAILURE: Build failed with an exception.

	* Where:
	Build file '/Users/Ben/dev/***/***-Android/***/build.gradle' line: 44

	* What went wrong:
	A problem occurred evaluating project ':***'.
	> Could not find method publishing() for arguments [build_ds8oxi3mj56eizl7bo7gvwsi7$_run_closure3@70b33256] on project ':***'.

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

	BUILD FAILED

	Total time: 4.249 secs

My modules build.grade looks like this:

	apply plugin: 'com.android.library'
	apply plugin: 'com.jfrog.bintray'

	android {
		[...]
	}

	bintray {
	    user = System.getenv('BINTRAY_USER')
	    key = System.getenv('BINTRAY_KEY')
	    publications = ['***']
	    pkg {
	        repo = 'maven'
	        name = '***'
	        userOrg = user
	        licenses = ['Apache-2.0']
	        vcsUrl = 'https://github.com/***.git'
	        labels = [***]
	        publicDownloadNumbers = false
	        version {
	            name = '***'
	            desc = '****'
	            vcsTag = '1.0.0'
	        }
	    }
	}

	publishing {
	    publications {
	        ***(MavenPublication) {
	            from components.java
	            groupId '***'
	            artifactId '***'
	            version '1.0.0'
	        }
	    }
	}

	dependencies {
		[...]
	}

What's wrong? Please help ;)

**Comment by benmarten** [comment]
Was missing `apply plugin: 'maven-publish'`

**Comment by iiasceri** [comment]
love ya

**Comment by avinitp68** [comment]
jj

**Comment by avinitp68** [comment]
Was Missing "apply plugin: 'maven-publish'" in project level build.gradle.  Worked like magic.
