### ISSUE TITLE
Publishing to two different packages in the same bintrayUpload task

### ISSUE THREAD

**Issue by larissanpa** [bintray/gradle-bintray-plugin#118]
Hi,

I am in the process of changing our gradle tasks to use Bintray instead of Maven Central. One of our modules generates two different jar libraries. In order to upload them to different repositories on Maven Central, we used filters (https://docs.gradle.org/current/userguide/maven_plugin.html#sub:multiple_artifacts_per_project). 

I have not found any reference on how to accomplish the same thing using Bintray (we have two different packages, one for each library). Is there a way to do such a thing?

Thanks in advance.

**Comment by eyalbe4** [comment]
@larissanpa, you can define two Publications, each of them publishes only one of the two artifacts. You can then configure the artifactoryPublish task to reference each time a different publication (using a project property for example). You may need to run *gradle artifactoryPublish* twice, each time uploading one of the artifacts. The Artifactory Plugin allows configuring multiple artifactoryPublish tasks, but they need to be in different sub-projects.

**Comment by larissanpa** [comment]
Thanks for the help, @eyalbe4! We were trying to avoid dividing this module into sub-projects, but it seems that we will have to do that anyway.
