### ISSUE TITLE
Could not upload files

### ISSUE THREAD

**Issue by msdx** [bintray/gradle-bintray-plugin#121]
I am a Chinese developer, last week some friends and I have met a problem that when we execute `bintrayUpload` to upload files, it would pause here, we waited a long time, but it didn't has any changed...
```
tarting to execute task ':bintrayUpload'
09:06:02.444 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter                                                                         ]                                                                               Determining if task ':bintrayUpload' is up-to-date
09:06:02.445 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter                                                                          ]                                                                               Executing task ':bintrayUpload' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
09:06:02.446 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter                                                                       ]                                                                               Executing actions for task ':bintrayUpload'.
09:06:02.456 [INFO] [org.gradle.api.Task] Found 0 configuration(s) to publish.
09:06:03.093 [DEBUG] [groovyx.net.http.HTTPBuilder] HEAD https://api.bintray.com/packages/msdx/maven/FirPublisher
09:06:03.279 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {s}->https://api.bintray.com
09:06:08.372 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator]                                                                               Connecting to api.bintray.com:443
09:06:08.903 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
09:06:08.913 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
09:06:08.913 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthenticatio]                                                                               Proxy auth state: UNCHALLENGED
09:06:08.915 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
09:06:08.915 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: HEAD /packages/msdx/maven/FirPublisher HTTP/1.1
09:06:08.918 [DEBUG] [org.apache.http.headers] >> HEAD /packages/msdx/maven/FirPublisher HTTP/1.1
09:06:08.919 [DEBUG] [org.apache.http.headers] >> Accept: */*
09:06:08.919 [DEBUG] [org.apache.http.headers] >> Authorization: Basic bXNkeDo3MGJmNjhhOWQwZDQzMjRkNzZkZjhlYjU1MzNiM2FkODU4MzMxNzZm
09:06:08.920 [DEBUG] [org.apache.http.headers] >> Host: api.bintray.com
09:06:08.920 [DEBUG] [org.apache.http.headers] >> Connection: Keep-Alive
09:06:09.923 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 200 OK
09:06:09.925 [DEBUG] [org.apache.http.headers] << HTTP/1.1 200 OK
09:06:09.925 [DEBUG] [org.apache.http.headers] << Server: nginx
09:06:09.926 [DEBUG] [org.apache.http.headers] << Date: Tue, 17 May 2016 01:06:09 GMT
09:06:09.927 [DEBUG] [org.apache.http.headers] << Content-Type: application/json
09:06:09.928 [DEBUG] [org.apache.http.headers] << Connection: keep-alive
09:06:09.930 [DEBUG] [org.apache.http.headers] << X-RateLimit-Limit: 1440
09:06:09.930 [DEBUG] [org.apache.http.headers] << X-RateLimit-Remaining: 0
09:06:09.962 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@61796fdb
09:06:09.968 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection 0.0.0.0:54720<->119.81.184.206:443 shut down
09:06:09.972 [DEBUG] [groovyx.net.http.HTTPBuilder] Response code: 200; found handler: com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure5_closure20_closure22@66e7c506
09:06:09.975 [DEBUG] [org.gradle.api.Task] Package 'FirPublisher' exists.
09:06:09.992 [DEBUG] [groovyx.net.http.HTTPBuilder] HEAD https://api.bintray.com/packages/msdx/maven/FirPublisher/versions/0.1.2
09:06:09.993 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {s}->https://api.bintray.com
09:06:10.004 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator]                                                                               Connecting to api.bintray.com:443
09:06:11.109 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
09:06:11.110 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
09:06:11.111 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthenticatio]                                                                               Proxy auth state: UNCHALLENGED
09:06:11.112 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
09:06:11.112 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: HEAD /packages/msdx/maven/FirPublisher/versions/0.1.2 HTTP/1.1
09:06:11.113 [DEBUG] [org.apache.http.headers] >> HEAD /packages/msdx/maven/FirPublisher/versions/0.1.2 HTTP/1.1
09:06:11.114 [DEBUG] [org.apache.http.headers] >> Accept: */*
09:06:11.115 [DEBUG] [org.apache.http.headers] >> Authorization: Basic bXNkeDo3MGJmNjhhOWQwZDQzMjRkNzZkZjhlYjU1MzNiM2FkODU4MzMxNzZm
09:06:11.115 [DEBUG] [org.apache.http.headers] >> Host: api.bintray.com
09:06:11.116 [DEBUG] [org.apache.http.headers] >> Connection: Keep-Alive
09:06:12.114 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 200 OK
09:06:12.115 [DEBUG] [org.apache.http.headers] << HTTP/1.1 200 OK
09:06:12.116 [DEBUG] [org.apache.http.headers] << Server: nginx
09:06:12.117 [DEBUG] [org.apache.http.headers] << Date: Tue, 17 May 2016 01:06:12 GMT
09:06:12.118 [DEBUG] [org.apache.http.headers] << Content-Type: application/json
09:06:12.119 [DEBUG] [org.apache.http.headers] << Connection: keep-alive
09:06:12.120 [DEBUG] [org.apache.http.headers] << X-RateLimit-Limit: 1440
09:06:12.121 [DEBUG] [org.apache.http.headers] << X-RateLimit-Remaining: 0
09:06:12.121 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@2c84d300
09:06:12.122 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection 0.0.0.0:54978<->119.81.184.206:443 shut down
09:06:12.123 [DEBUG] [groovyx.net.http.HTTPBuilder] Response code: 200; found handler: com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure6_closure26_closure28@4184d8e3
09:06:12.123 [DEBUG] [org.gradle.api.Task] Version 'msdx/maven/FirPublisher/0.1.2' exists.
09:06:12.165 [INFO] [org.gradle.api.Task] Uploading to https://api.bintray.com/content/msdx/maven/FirPublisher/0.1.2/com/githang/fir/0.1.2/fir-0.1.2.jar...
09:06:12.201 [DEBUG] [groovyx.net.http.HTTPBuilder] PUT https://api.bintray.com/content/msdx/maven/FirPublisher/0.1.2/com/githang/fir/0.1.2/fir-0.1.2.jar
09:06:12.204 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {s}->https://api.bintray.com
09:06:12.209 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator]                                                                               Connecting to api.bintray.com:443
09:06:14.301 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
09:06:14.302 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
09:06:14.303 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthenticatio]                                                                               Proxy auth state: UNCHALLENGED
09:06:14.304 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
09:06:14.305 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: PUT /content/msdx/maven/FirPublisher/0.1.2/com/githang/fir/0.1.2/fir-0.1.2.jar HTTP/1.1
09:06:14.305 [DEBUG] [org.apache.http.headers] >> PUT /content/msdx/maven/FirPublisher/0.1.2/com/githang/fir/0.1.2/fir-0.1.2.jar HTTP/1.1
09:06:14.305 [DEBUG] [org.apache.http.headers] >> Accept: */*
09:06:14.306 [DEBUG] [org.apache.http.headers] >> Authorization: Basic bXNkeDo3MGJmNjhhOWQwZDQzMjRkNzZkZjhlYjU1MzNiM2FkODU4MzMxNzZm
09:06:14.306 [DEBUG] [org.apache.http.headers] >> Content-Length: 32584
09:06:14.306 [DEBUG] [org.apache.http.headers] >> Content-Type: application/octet-stream
09:06:14.307 [DEBUG] [org.apache.http.headers] >> Host: api.bintray.com
09:06:14.307 [DEBUG] [org.apache.http.headers] >> Connection: Keep-Alive
> Building 90% > :bintrayUpload
```
I do not know what happened, and how can I solve this problem ?

**Comment by msdx** [comment]
Full log about `bintrayUpload`:
                                                                              Starting to execute task ':bintrayUpload'
09:26:41.332 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter                                                                         ]                                                                               Determining if task ':bintrayUpload' is up-to-date
09:26:41.333 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter                                                                          ]                                                                               Executing task ':bintrayUpload' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
09:26:41.333 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter                                                                       ]                                                                               Executing actions for task ':bintrayUpload'.
09:26:41.352 [INFO] [org.gradle.api.Task] Found 0 configuration(s) to publish.
09:26:41.645 [DEBUG] [groovyx.net.http.HTTPBuilder] HEAD https://api.bintray.com/packages/msdx/maven/FirPublisher
09:26:41.694 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {s}->https://api.bintray.com
09:26:41.737 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator]                                                                               Connecting to api.bintray.com:443
09:26:42.205 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
09:26:42.211 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
09:26:42.212 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthenticatio]                                                                               Proxy auth state: UNCHALLENGED
09:26:42.213 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
09:26:42.213 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: HEAD /packages/msdx/maven/FirPublisher HTTP/1.1
09:26:42.215 [DEBUG] [org.apache.http.headers] >> HEAD /packages/msdx/maven/FirPublisher HTTP/1.1
09:26:42.215 [DEBUG] [org.apache.http.headers] >> Accept: */*
09:26:42.216 [DEBUG] [org.apache.http.headers] >> Authorization: Basic bXNkeDo3MGJmNjhhOWQwZDQzMjRkNzZkZjhlYjU1MzNiM2FkODU4MzMxNzZm
09:26:42.217 [DEBUG] [org.apache.http.headers] >> Host: api.bintray.com
09:26:42.218 [DEBUG] [org.apache.http.headers] >> Connection: Keep-Alive
09:26:42.904 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 200 OK
09:26:42.906 [DEBUG] [org.apache.http.headers] << HTTP/1.1 200 OK
09:26:42.907 [DEBUG] [org.apache.http.headers] << Server: nginx
09:26:42.908 [DEBUG] [org.apache.http.headers] << Date: Tue, 17 May 2016 01:26:42 GMT
09:26:42.909 [DEBUG] [org.apache.http.headers] << Content-Type: application/json
09:26:42.910 [DEBUG] [org.apache.http.headers] << Connection: keep-alive
09:26:42.912 [DEBUG] [org.apache.http.headers] << X-RateLimit-Limit: 1440
09:26:42.913 [DEBUG] [org.apache.http.headers] << X-RateLimit-Remaining: 0
09:26:42.925 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@34d3f381
09:26:42.926 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection 0.0.0.0:44338<->119.81.184.206:443 shut down
09:26:42.928 [DEBUG] [groovyx.net.http.HTTPBuilder] Response code: 200; found handler: com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure5_closure20_closure22@5544c8d9
09:26:42.930 [DEBUG] [org.gradle.api.Task] Package 'FirPublisher' exists.
09:26:42.937 [DEBUG] [groovyx.net.http.HTTPBuilder] HEAD https://api.bintray.com/packages/msdx/maven/FirPublisher/versions/0.1.2
09:26:42.939 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {s}->https://api.bintray.com
09:26:42.943 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator]                                                                               Connecting to api.bintray.com:443
09:26:44.366 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
09:26:44.367 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
09:26:44.368 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthenticatio]                                                                               Proxy auth state: UNCHALLENGED
09:26:44.369 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
09:26:44.369 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: HEAD /packages/msdx/maven/FirPublisher/versions/0.1.2 HTTP/1.1
09:26:44.370 [DEBUG] [org.apache.http.headers] >> HEAD /packages/msdx/maven/FirPublisher/versions/0.1.2 HTTP/1.1
09:26:44.370 [DEBUG] [org.apache.http.headers] >> Accept: */*
09:26:44.370 [DEBUG] [org.apache.http.headers] >> Authorization: Basic bXNkeDo3MGJmNjhhOWQwZDQzMjRkNzZkZjhlYjU1MzNiM2FkODU4MzMxNzZm
09:26:44.370 [DEBUG] [org.apache.http.headers] >> Host: api.bintray.com
09:26:44.371 [DEBUG] [org.apache.http.headers] >> Connection: Keep-Alive
09:26:45.075 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 200 OK
09:26:45.076 [DEBUG] [org.apache.http.headers] << HTTP/1.1 200 OK
09:26:45.077 [DEBUG] [org.apache.http.headers] << Server: nginx
09:26:45.078 [DEBUG] [org.apache.http.headers] << Date: Tue, 17 May 2016 01:26:45 GMT
09:26:45.079 [DEBUG] [org.apache.http.headers] << Content-Type: application/json
09:26:45.080 [DEBUG] [org.apache.http.headers] << Connection: keep-alive
09:26:45.080 [DEBUG] [org.apache.http.headers] << X-RateLimit-Limit: 1440
09:26:45.081 [DEBUG] [org.apache.http.headers] << X-RateLimit-Remaining: 0
09:26:45.083 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@4fdc21d
09:26:45.084 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection 0.0.0.0:44468<->119.81.184.206:443 shut down
09:26:45.085 [DEBUG] [groovyx.net.http.HTTPBuilder] Response code: 200; found handler: com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure6_closure26_closure28@5bf831c8
09:26:45.087 [DEBUG] [org.gradle.api.Task] Version 'msdx/maven/FirPublisher/0.1.2' exists.
09:26:45.102 [INFO] [org.gradle.api.Task] Uploading to https://api.bintray.com/content/msdx/maven/FirPublisher/0.1.2/com/githang/fir/0.1.2/fir-0.1.2.jar...
09:26:45.124 [DEBUG] [groovyx.net.http.HTTPBuilder] PUT https://api.bintray.com/content/msdx/maven/FirPublisher/0.1.2/com/githang/fir/0.1.2/fir-0.1.2.jar
09:26:45.127 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {s}->https://api.bintray.com
09:26:45.133 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator]                                                                               Connecting to api.bintray.com:443
09:26:45.587 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
09:26:45.588 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
09:26:45.589 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthenticatio]                                                                               Proxy auth state: UNCHALLENGED
09:26:45.592 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
09:26:45.593 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: PUT /content/msdx/maven/FirPublisher/0.1.2/com/githang/fir/0.1.2/fir-0.1.2.jar HTTP/1.1
09:26:45.593 [DEBUG] [org.apache.http.headers] >> PUT /content/msdx/maven/FirPublisher/0.1.2/com/githang/fir/0.1.2/fir-0.1.2.jar HTTP/1.1
09:26:45.594 [DEBUG] [org.apache.http.headers] >> Accept: */*
09:26:45.594 [DEBUG] [org.apache.http.headers] >> Authorization: Basic bXNkeDo3MGJmNjhhOWQwZDQzMjRkNzZkZjhlYjU1MzNiM2FkODU4MzMxNzZm
09:26:45.595 [DEBUG] [org.apache.http.headers] >> Content-Length: 32584
09:26:45.595 [DEBUG] [org.apache.http.headers] >> Content-Type: application/octet-stream
09:26:45.595 [DEBUG] [org.apache.http.headers] >> Host: api.bintray.com
09:26:45.596 [DEBUG] [org.apache.http.headers] >> Connection: Keep-Alive
09:43:25.769 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection 0.0.0.0:44728<->119.81.184.206:443 closed
09:43:25.770 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Closing the connection.
09:43:25.771 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection 0.0.0.0:44728<->119.81.184.206:443 closed
09:43:25.772 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection 0.0.0.0:44728<->119.81.184.206:443 shut down
09:43:25.773 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@421714bd
09:43:25.775 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter                                                                    ]                                                                               Finished executing task ':bintrayUpload'
09:43:25.776 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :bintrayUpload FAILED
09:43:25.776 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :bintrayUpload (Thread[Daemon worker Thread 2,5,main]) completed. Took 16 mins 44.445 secs.
09:43:25.777 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 2,5,main]] finished, busy: 16 mins 45.259 secs, idle: 0.015 secs
09:43:25.778 [ERROR] [org.gradle.BuildExceptionReporter] 
09:43:25.779 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:43:25.779 [ERROR] [org.gradle.BuildExceptionReporter] 
09:43:25.780 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
09:43:25.780 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':bintrayUpload'.
09:43:25.781 [ERROR] [org.gradle.BuildExceptionReporter] > java.net.SocketException: 连接超时
09:43:25.781 [ERROR] [org.gradle.BuildExceptionReporter] 
09:43:25.782 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
09:43:25.783 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
09:43:25.783 [LIFECYCLE] [org.gradle.BuildResultLogger] 
09:43:25.783 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
09:43:25.784 [LIFECYCLE] [org.gradle.BuildResultLogger] 
09:43:25.784 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 16 mins 47.734 secs
09:43:25.785 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Plugin Resolution Cache (/home/haohang/.gradle/caches/2.2/plugin-resolution) was closed 0 times.
09:43:25.785 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on buildscript class cache for build file '/workspace/project/fir-publish/build.gradle' (/home/haohang/.gradle/caches/2.2/scripts/build_bfjq056u933z3htx62wq1y9y9/ProjectScript/buildscript).
09:43:25.785 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on no_buildscript class cache for build file '/workspace/project/fir-publish/build.gradle' (/home/haohang/.gradle/caches/2.2/scripts/build_bfjq056u933z3htx62wq1y9y9/ProjectScript/no_buildscript).
09:43:25.786 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on buildscript class cache for script '/workspace/project/fir-publish/groovy.gradle' (/home/haohang/.gradle/caches/2.2/scripts/groovy_bqtt3j3z7y6chne794fytf7b3/DefaultScript/buildscript).
09:43:25.786 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on no_buildscript class cache for script '/workspace/project/fir-publish/groovy.gradle' (/home/haohang/.gradle/caches/2.2/scripts/groovy_bqtt3j3z7y6chne794fytf7b3/DefaultScript/no_buildscript).
09:43:25.787 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache                                                                              ]                                                                               Closing cache artifact-at-repository.bin (/home/haohang/.gradle/caches/modules-2/metadata-2.14/artifact-at-repository.bin)
09:43:25.787 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache                                                                              ]                                                                               Closing cache module-metadata.bin (/home/haohang/.gradle/caches/modules-2/metadata-2.14/module-metadata.bin)
09:43:25.787 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/home/haohang/.gradle/caches/modules-2).
09:43:25.788 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager                                                                       ]                                                                               Stopping 0 compiler daemon(s).
09:43:25.788 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager                                                                        ]                                                                               Stopped 0 compiler daemon(s).
09:43:25.789 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache                                                                              ]                                                                               Closing cache fileSnapshots.bin (/workspace/project/fir-publish/.gradle/2.2/taskArtifacts/fileSnapshots.bin)
09:43:25.790 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache                                                                              ]                                                                               Closing cache fileHashes.bin (/workspace/project/fir-publish/.gradle/2.2/taskArtifacts/fileHashes.bin)
09:43:25.790 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache                                                                              ]                                                                               Closing cache taskArtifacts.bin (/workspace/project/fir-publish/.gradle/2.2/taskArtifacts/taskArtifacts.bin)
09:43:25.790 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on task history cache (/workspace/project/fir-publish/.gradle/2.2/taskArtifacts).
09:43:25.791 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory                                         ]                                                                               In-memory dependency metadata cache closed. Repos cached: 2, cache instances: 2, modules served from cache: 0, artifacts: 0
09:43:25.792 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory                                                      ]                                                                               Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
09:43:25.792 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory                                                      ]                                                                               Resolved configuration cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
09:43:25.792 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory                                           ]                                                                               Deleted 2 resolution results binary files in 0.0 secs
09:43:25.793 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
09:43:26.190 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder                                                                             ]                                                                               Dispatching close input message: CloseInput[id=a726f510-4478-49ff-b970-1f52f5bdb906.2]
09:43:26.190 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection]thread 12: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
09:43:26.195 [INFO] [org.gradle.launcher.daemon.client.DaemonClient] Received result DaemonCommandResult[type=CommandFailure, value=org.gradle.launcher.exec.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':bintrayUpload'.] from daemon DaemonInfo{pid=30712, address=[cbed45c6-8285-4aaa-8a88-e698bf88ed63 port:40241, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]], idle=true, context=DefaultDaemonContext[uid=69ceae6d-7014-4cab-9645-47897595cd21,javaHome=/usr/lib/jvm/java-8-openjdk-amd64,daemonRegistryDir=/home/haohang/.gradle/daemon,pid=30712,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]}.
09:43:26.196 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection]thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
09:43:26.198 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection]thread 1: connection stop
```

**Comment by eyalbe4** [comment]
@msdx,
It looks like your build agent fails to access Bintray. Are you able to upload your files directly by using Bintray's REST API (through curl or JFrog CLI)?

**Comment by msdx** [comment]
@eyalbe4 
I found the reason. **GFW** caused it...
I've solved this problem by set gradle proxy configuration.
btw, thank you very much.
