### ISSUE TITLE
HTTP/1.1 404 Not Found [message:Repo 'maven' was not found]

### ISSUE THREAD

**Issue by ouyangzn** [bintray/gradle-bintray-plugin#141]
I got this error when i executed bintrayUpload:
HTTP/1.1 404 Not Found [message:Repo 'maven' was not found]
How to solve it?

### Here is my build.gradle:

`
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:2.1.0'
    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
    // 提交到jcenter仓库使用的插件
    classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
    classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.3'
  }
}`
### and 
`
apply plugin: 'com.github.dcendents.android-maven'
apply plugin: 'com.jfrog.bintray'

version = VERSION
// Maven Group ID for the artifact，一般填你唯一的包名
group = GROUP_ID

def siteUrl = 'https://github.com/ouyangzn/BaseRecyclerAdapter'   // 项目的主页
def gitUrl = 'git@github.com:ouyangzn/BaseRecyclerAdapter.git'   // Git仓库的url
install {
  repositories.mavenInstaller {
    // This generates POM.xml with proper parameters
    pom {
      project {
        packaging 'aar'
        // Add your description here 项目的描述
        name DESCRIPTION
        url siteUrl
        // Set your license
        licenses {
          license {
            name 'The Apache Software License, Version 2.0'
            url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
          }
        }
        developers {
          developer {
            //填写的一些基本信息
            id USER
            name 'Z、ero'
            email 'ouyangzhaoneng@gmail.com'
          }
        }
        scm {
          connection gitUrl
          developerConnection gitUrl
          url siteUrl
        }
      }
    }
  }
}

// build a jar with source files
task sourcesJar(type: Jar) {
  from android.sourceSets.main.java.srcDirs
  classifier = 'sources'
}

task javadoc(type: Javadoc) {
  failOnError false
  source = android.sourceSets.main.java.sourceFiles
  classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
  classpath += configurations.compile
}

// build a jar with javadoc
task javadocJar(type: Jar, dependsOn: javadoc) {
  classifier = 'javadoc'
  from javadoc.destinationDir
}

artifacts {
  archives sourcesJar
  archives javadocJar
}
javadoc {
  options {
    encoding "UTF-8"
    charSet 'UTF-8'
    author true
    version VERSION
    links "http://docs.oracle.com/javase/7/docs/api"
    title 'BaseRecyclerAdapter'
  }
}

Properties properties = new Properties()
properties.load(project.rootProject.file('local.properties').newDataInputStream())
bintray {
  user = properties.getProperty("bintray.user")
  key = properties.getProperty("bintray.apikey")
  configurations = ['archives']
  pkg {
    repo = "maven"
    // project name in jcenter
    name = ARTIFACT_ID_LIBRARY
    websiteUrl = siteUrl
    vcsUrl = gitUrl
    licenses = ["Apache-2.0"]
    publish = true
  }
}
`

**Comment by beyondbright** [comment]
maven是repo名字，在bintray.com上建一个repo，用对应的名字即可

**Comment by eyalbe4** [comment]
@ouyangzn,
Since this functionality is very basic, I'm guessing that there's no repository named "maven" for the Bintray user returned by the "bintray.user" project property.

**Comment by ouyangzn** [comment]
@beyondbright @eyalbe4 thanks，I have resolved this.

**Comment by AdamSHurwitz** [comment]
@ouyangzn, please share with us how you resolves this as I am still having this issue.

```
ext {
    bintrayRepo = 'maven'
    bintrayName = 'custom-ripple-view'

    publishedGroupId = 'com.github.adamshurwitz.customrippleview'
    libraryName = 'CustomRippleView'
    artifact = 'custom-ripple-view'

    libraryDescription = 'Custom Ripple View for Android'

    siteUrl = 'https://github.com/adamshurwitz/customrippleview'
    gitUrl = 'https://github.com/adamshurwitz/customrippleview.git'

    libraryVersion = '1.0'

    developerId = 'adamhurwitz'
    developerName = 'Adam Hurwitz'
    developerEmail = 'adamscotthurwitz@gmail.com'

    licenseName = 'The Apache Software License, Version 2.0'
    licenseUrl = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
    allLicenses = ["Apache-2.0"]
}
```

**Comment by ouyangzn** [comment]
@AdamSHurwitz 
You should write repository rightly, ensure there is a repository named maven, or change `bintrayRepo = 'maven'`  to an exists repository's name.
there is my repository:
![qq 20170531114446](https://cloud.githubusercontent.com/assets/8808376/26615068/e56dd548-45f6-11e7-94ef-8e39cc7e0f1b.png)

So if I use repository 'maven', it will be  `HTTP/1.1 404 Not Found [message:Repo 'maven' was not found]` ,  because it's not exists. I changed `repo = "maven"` to `repo = " Android-lib"`, it's ok.

**Comment by dwkim891220** [comment]
```
publish {
    repoName = 'something'
}
```

repoName is force set maven when repoName is empty.
should set your repoName!!!

**Comment by tasomaniac** [comment]
In my case it was because case-sensitivity. I thought it wouldn't matter but cases matter.
