### ISSUE TITLE
message:Repo 'maven' was not found

### ISSUE THREAD

**Issue by dmitrikudrenko** [bintray/gradle-bintray-plugin#143]
When I try to upload my android library, I get an error
```
Execution failed for task ':library:bintrayUpload'.
> Could not create package 'dmitrikudrenko/maven/ContentManager': HTTP/1.1 404 Not Found [message:Repo 'maven' was not found]
```
What do I make wrong?

**Comment by dmitrikudrenko** [comment]
I created manually repository with name 'maven' in my bintray account and it solved my problem

**Comment by Deepankur-Sadana** [comment]
@dmitrikudrenko saved my day:)

**Comment by geniushkg** [comment]
The actual problem is in gradle file declaration
if you have something like this :
ext {
    bintrayRepo = 'maven'
    bintrayName = 'your_defined_name'

means gradle is looking for repository named : maven and package name : your_defined_name ,

you can replace maven in gradle file with name of your repository in jcenter

@dmitrikudrenko  is also true in same sense. :+1:

**Comment by ch-muhammad-adil** [comment]
@dmitrikudrenko thank you so much. it really saved me.. I was so much frustrated because of this error for many days.

**Comment by suragch** [comment]
I also ran into this problem. The above comments solved the problem. [Here is my longer solution.](http://stackoverflow.com/a/43951025/3681880)

**Comment by AdamSHurwitz** [comment]
I tried @geniushkg's solution. My build appears stuck at 98%.

<img width="839" alt="screen shot 2017-05-21 at 7 01 59 pm" src="https://cloud.githubusercontent.com/assets/3938076/26289860/1170351a-3e58-11e7-8270-2e1306049f3e.png">

**Comment by gamma-co** [comment]
@dmitrikudrenko thanks;
you save my day; 👍
