### ISSUE TITLE
Artifacts missing

### ISSUE THREAD

**Issue by jameskleeh** [bintray/gradle-bintray-plugin#145]
See my `build.gradle` here: https://github.com/jameskleeh/groovy-excel-builder/blob/master/build.gradle

`bintrayUpload` succeeded, however no files were pushed. Any ideas? Running Gradle 3.1.

https://bintray.com/schlogen/com.jameskleeh/excel-builder/0.1.0#files

Here is the travis build that did it:

https://travis-ci.org/jameskleeh/groovy-excel-builder/builds/163593136

**Comment by eyalbe4** [comment]
@jameskleeh,
Can you please try adding the *version* closure inside *pkg* as described in the [readme](https://github.com/bintray/gradle-bintray-plugin/blob/master/README.md)? Let us know if this works for you.

**Comment by jameskleeh** [comment]
So for my case, something like this?
```
version {
        name = project.version
        desc = 'Groovy Excel Builder ' + project.version
        released  = new Date()
        vcsTag = 'v' + project.version
}
````

**Comment by jameskleeh** [comment]
@eyalbe4 I realized that I saw this previously and hit discard as I wasn't sure what it was.

Notice: You have 4 unpublished item(s) for this version (expiring in 6 days and 22 hours) Discard | Publish

I added `publish=true` and all is well without the `version` block. Thanks!
