### ISSUE TITLE
Adding githubRepo to `bintray{}` triggers an error 

### ISSUE THREAD

**Issue by PLNech** [bintray/gradle-bintray-plugin#148]
Adding `githubRepo` to the `bintray` closure triggers an error: 
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/user/project/module/build.gradle' line: 170

* What went wrong:
A problem occurred evaluating project ':module'.
> Could not set unknown property 'githubRepo' for object of type com.jfrog.bintray.gradle.BintrayExtension
```

I'm using bintray v1.7:
```groovy
plugins {
    id "com.jfrog.bintray" version "1.7"
}
```

Shouldn't #101 have fixed #31 in v>1.6?

**Comment by eyalbe4** [comment]
@PLNech, please try defining the *githubRepo* property inside the *pkg* closure as defined in [this](https://github.com/bintray/gradle-bintray-plugin/blob/master/src/test/resources/gradle/buildFiles/create_package_and_version_with_configuration.gradle) closure. This snippet closure was used to test version 1.7.2 of the plugin.

**Comment by PLNech** [comment]
Oh thanks @eyalbe4, I don't know how I misunderstood that it should go to the `bintray` closure 😞
