### ISSUE TITLE
HTTP/1.1 404 Not Found [message:Repo 'maven' was not found]

### ISSUE THREAD

**Issue by JoxHero** [bintray/gradle-bintray-plugin#150]
I got this error when i executed bintrayUpload:
HTTP/1.1 404 Not Found [message:Repo 'maven' was not found]
How to solve it?

apply plugin: 'com.android.library'
apply plugin: 'com.github.dcendents.android-maven'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    testCompile 'junit:junit:4.12'
}

group = 'com.libraryuploadtest'
version = '0.1'

install {
    repositories.mavenInstaller {
        pom.project {
            name 'libraryuploadtest'
            description 'A wrapper library for basic functions of Google Play Services APIs'
            url 'https://github.com/googlesamples/easygoogle'
            inceptionYear '2015'

            packaging 'aar'
            groupId 'com.libraryuploadtest'
            artifactId 'libraryuploadtest'
            version '0.1'

            licenses {
                license {
                    name 'The Apache Software License, Version 2.0'
                    url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    distribution 'repo'
                }
            }
            scm {
                connection 'https://github.com/googlesamples/easygoogle.git'
                url 'https://github.com/googlesamples/easygoogle'

            }
            developers {
                developer {
                    name 'Google'
                }
            }
        }
    }
}

bintray {
    user = project.hasProperty('bintrayUser') ? project.property('bintrayUser') : System.getenv('BINTRAY_USER')
    key = project.hasProperty('bintrayApiKey') ? project.property('bintrayApiKey') : System.getenv('BINTRAY_API_KEY')
    configurations = ['archives']
    pkg {
        repo = 'maven'
        name = 'libraryuploadtest'
        userOrg = user
        licenses = ['Apache-2.0']
        vcsUrl = 'https://github.com/bintray/gradle-bintray-plugin.git'
        version {
            name = '0.1'
            desc = 'Gradle Bintray Plugin 1.0 final'
            vcsTag = '0.1'
            attributes = ['gradle-plugin': 'com.use.less:com.use.less.gradle:gradle-useless-plugin']
        }
    }
}

并且 bintray上的repo 确实是maven

**Comment by geniushkg** [comment]
Its because you defined to find a repo name maven over here

```
pkg {
repo = 'maven'
name = 'libraryuploadtest'
```


now replace maven with repo name you  create in jcenter web dashboard or create new repo name maven

**Comment by JoxHero** [comment]
@geniushkg thanks，This problem has been solved，userOrg to write my organization name

**Comment by eyalbe4** [comment]
Happy to hear that @JoxHero and thanks for the help @geniushkg.
I'm closing this issue with your permission.
