### ISSUE TITLE
Feature request: Deploy to any jCenter-Like server

### ISSUE THREAD

**Issue by walfud** [bintray/gradle-bintray-plugin#153]
I have setup a artifactory(OSS) docker in my company. So how should I use this plugin to upload the aar to my artifactory server?

**Comment by eyalbe4** [comment]
We recommend using the [Gradle Artifactory Plugin](https://www.jfrog.com/confluence/display/RTF/Gradle+Artifactory+Plugin) for gradle artifacts deployment, dependencies resolution and build-info publication to Artifactory.

**Comment by walfud** [comment]
ok, I found there is [`apiUrl = extension.apiUrl`](https://github.com/bintray/gradle-bintray-plugin/blob/322f2a6868531ca98a81dab39665daaf9d1a0f97/src/main/groovy/com/jfrog/bintray/gradle/BintrayPlugin.groovy#L32) in BintrayPlugin. Can I specified my server's url by `apiUrl`?

**Comment by eyalbe4** [comment]
No @walfud, the Gradle Bintray Plugin can only be used with Bintray. Please use the Gradle Artifactory Plugin for Artifactory deployment.

**Comment by walfud** [comment]
Thank you very much
