### ISSUE TITLE
HTTP/1.1 401 Unauthorized [message:This resource requires authentication]

### ISSUE THREAD

**Issue by JoaquimLey** [bintray/gradle-bintray-plugin#154]
Everytime I try to upload via Gradle task following the tutorials I always get this message:

Execution failed for task ':lib:bintrayUpload'.
Could not create version '0.1.0': HTTP/1.1 401 Unauthorized [message:This resource requires authentication]

- Repo: https://github.com/JoaquimLey/FabOptions
- Config scripts: https://github.com/JoaquimLey/jcenter-configs

**Comment by eyalbe4** [comment]
@JoaquimLey,
Did you try running the [plugin examples](https://github.com/bintray/bintray-examples/tree/master/gradle-bintray-plugin-examples)? If they work for you, then you could compare them to your project to pinpoint the issue.

**Comment by JoaquimLey** [comment]
Hello @eyalbe4 after a lot of trial and error I was able to write my own script and get everything to work 😉.
Thanks

**Comment by ssdd1886** [comment]
can you please post your build.gradle bintray settings? i've stumbled this issue myself and unable to find a solution for several days now...:(

**Comment by HunterPillu** [comment]
I am facing this error .can anyone help me around 

Could not upload to 'https://api.bintray.com/content/mobifly/publicdemo/TryMash4/1.1/in/mobifly/mobiflysdk/app/1.1/app-1.1-javadoc.jar': HTTP/1.1 401 Unauthorized [message:This res
ource requires authentication]

**Comment by JoaquimLey** [comment]
@ssdd1886 @HunterPillu Sorry for the late response: 

I wrote the script and open sourced it:

https://github.com/JoaquimLey/jcenter-config

**Comment by KaviPaviTwinsS** [comment]
Could not upload to 'https://api.bintray.com/content/dofnpt/CustomWidget/developer.mylibrary/1.0.0/developer/mylibrary/mylibrary/1.0.0/mylibrary-1.0.0-javadoc.jar': HTTP/1.1 401 Unauthorized [message:This resource requires authentication]

**Comment by KaviPaviTwinsS** [comment]
Could not upload to 'https://api.bintray.com/content/dofnpt/CustomWidget/developer.mylibrary/1.0.0/developer/mylibrary/mylibrary/1.0.0/mylibrary-1.0.0-javadoc.jar': HTTP/1.1 401 Unauthorized [message:This resource requires authentication]

**Comment by KaviPaviTwinsS** [comment]
hi,
https://github.com/JoaquimLey/jcenter-config

 This script is not working

**Comment by JoaquimLey** [comment]
It is working, you have to read the documentation over there and update with your details.

**Comment by HunterPillu** [comment]
Why am I getting this mail ????
