### ISSUE TITLE
Unable to upload files: Debian Distribution [etc] Required

### ISSUE THREAD

**Issue by BClark09** [bintray/gradle-bintray-plugin#157]
Hello,

I am trying to upload .deb files into a debian repo, but can't find any examples on doing so.

```
bintray {
  user = System.env.BINTRAY_USER
  key = System.env.BINTRAY_API_KEY

  dryRun = false
  publish = true    
  override = true

  filesSpec {
    from ('build/distributions') { include '*.deb' }
    into '/'
  }

  pkg {
    repo = 'x'
    name = 'y'
    userOrg = 'z'
    desc = 'Packages for y'

    attributes = ['deb_distribution': 'development', 'deb_component': 'main', 'deb_architecture': 'all']
  }
}
```

Unfortunately, this provides the following error:

```
HTTP/1.1 400 Bad Request [message:Unable to upload files: Debian distribution, component and architecture must be specified.
```

I assume that the attributes are correct but are set at the wrong level. How do I set these on the upload?

**Comment by gschueler** [comment]
Is there any solution to this?

**Comment by eyalbe4** [comment]
@gschueler
The *attributes* list is expected to be inside the *version* closure as described in the plugin [documentation](https://github.com/bintray/gradle-bintray-plugin/blob/master/README.md).
In the sample in this Issue's body, the *attributes* list in inside the *pkg* closure.
Please let us know if this works for you.

**Comment by gschueler** [comment]
@eyalbe4 thanks for response, it didn't work in the version closure either.  the `deb_distribution` was added as an attribute to the package, but the upload failed with `Unable to upload files: Debian distribution, component and architecture must be specified.`

According to the documentation, the only way works is if used in the "matrix components" of the URL, but there doesn't seem to be any way to set that in the gradle configuration.

**Comment by eyalbe4** [comment]
I see @gschueler,
Let me investigate this. I'll reply back soon.

**Comment by eyalbe4** [comment]
@gschueler,
We intend to enhance the *bintray* DSL, so that it supports defining the debian matrix components.
We'll update soon.

**Comment by gschueler** [comment]
@eyalbe4 sounds good, thank you!

**Comment by eyalbe4** [comment]
@gschueler,
Just wanted to let you know that we pushed [this](https://github.com/bintray/gradle-bintray-plugin/commit/ef2540fd10248223ee442321502ab2060949e71f) commit for supporting debian packages upload.
We still need to add the README documentation to describe how to use the new functionality and of course publish a new release of the plugin.
We'll let you know when done.

**Comment by gschueler** [comment]
@eyalbe4 thanks

**Comment by eyalbe4** [comment]
@gschueler,
Version 1.8.0 has just been released and includes Debian package support.
The README includes more details.
We'd appreciate your feedback for this.
