### ISSUE TITLE
bintrayUpload gradle task throws 'could not create package' error

### ISSUE THREAD

**Issue by Smekalisty** [bintray/gradle-bintray-plugin#160]
> Error:Execution failed for task ':bintrayUpload'.
> > Could not create package 'user_name/pos/sdk': HTTP/1.1 404 Not Found [message:Repo 'pos' was not found]

```
buildscript {
    repositories {
        jcenter()
    }

    apply plugin: 'java'

    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
    }
}

plugins {
    id 'com.jfrog.bintray' version '1.7.3'
}

bintray {
    user = 'user_name'
    key = 'api_key'
    pkg {
        repo = 'pos'
        name = 'sdk'
        licenses = ['license_name']
        vcsUrl = 'my_url'
        version {
            name = '0.0.1'
        }
    }
    filesSpec {
        from 'sdk/build/outputs/aar/sdk-release.aar'
        into '.'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
Thanks

**Comment by eyalbe4** [comment]
@Smekalisty,
I assume there's no *pos* repository in Bintray for this user, as the Bintray response message states.

**Comment by Smekalisty** [comment]
Please see the user name 'donov'
Thanks

**Comment by Smekalisty** [comment]
Maybe it helps somebody; from plugin Getting Started:
>userOrg = 'bintray_user'

Need to fill solely _organisation name_, and not _bintray user name_, and for me this field is required, not optional
Thanks Eyal @eyalbe4 for help by email

**Comment by Reza-saeedi** [comment]
hi,
i have same problem
i created 'maven' repository in bintray.com but i got this error when i want publish my library

Error:Execution failed for task ':testlib:bintrayUpload'.
> Could not create package 'reza-saeedi/maven/testlib': HTTP/1.1 404 Not Found [message:Repo 'maven' was not found]

this is my gradle:
`apply plugin: 'com.android.library'
apply plugin: 'com.jfrog.bintray'
apply plugin: 'com.github.dcendents.android-maven'

android {
    compileSdkVersion 26



    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:converter-gson:2.2.0'
    implementation 'com.android.support:appcompat-v7:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}

task sourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    classifier = 'sources'
}

task javadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
    classpath += fileTree(dir: "$buildDir/intermediates/exploded-aar/", include:"**/classes.jar")
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}
artifacts {
    archives javadocJar
    archives sourcesJar
}
def siteUrl = 'https://github.com/bintray/bintray-examples'
def gitUrl = 'https://github.com/bintray/bintray-examples.git'

bintray {
    user = 'reza-saeedi'
    key = '**********'
 pkg {
        repo  = 'maven'
        name = project.name
        desc = 'Bintray aar publishing example'
        websiteUrl = siteUrl
        issueTrackerUrl = 'https://github.com/bintray/bintray-examples/issues'
        vcsUrl = gitUrl
        licenses = ['Apache-2.0']
        labels = ['aar', 'android', 'example']
        publicDownloadNumbers = true
    }
}`

![capture](https://user-images.githubusercontent.com/18268741/35567154-47873de4-05d9-11e8-9ea5-c2f6ede4865b.PNG)
