### ISSUE TITLE
jcenter upload error

### ISSUE THREAD

**Issue by b12kab** [bintray/gradle-bintray-plugin#172]
I'm getting an error with uploading my files into Jcenter. Specifically, this error:

```
* What went wrong:
Execution failed for task ':tmdblibrary:bintrayUpload'.
> Could not upload to 'https://api.bintray.com/content/b12kab/maven/tmdblibrary/tmdblibrary/tmdblibrary/tmdblibrary/unspecified/tmdblibrary-unspecified.pom': HTTP/1.1 400 Bad Request [message:Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path 'tmdblibrary/tmdblibrary/unspecified/tmdblibrary-unspecified.pom']

```

[Here](https://gist.github.com/b12kab/c141e9ade39ee4b6adff9dc4c2eea4cf) is the project, library and jcenter upload gradle files.

Any help would be greatly appreciated :)

Note: bintrayUser as well as bintrayApikey variables are in my global gradle.properties file. Those variables work fine as tested with the commented out parts in jcenter-try2.gradle.

**Comment by eyalbe4** [comment]
@b12kab,
It looks like the upload path for your pom file does not include a version. Take a look at the upload log message, just before the Bintray response, and you'll notice the word "unspecified" in the pom file name and in its path. This is probably because your build.gradle does not include the version property.
You can use the [bibtray-gradle-examples](https://github.com/bintray/bintray-examples/tree/master/gradle-bintray-plugin-examples) to help you build your build.gradle properly.

**Comment by b12kab** [comment]
I [updated](https://gist.github.com/b12kab/c141e9ade39ee4b6adff9dc4c2eea4cf) the version enclosure's name. Altering that solved one part of the problem, but I still get an error. 

When there isn't a version existing in Bintray, I get this error:
```
Execution failed for task ':tmdblibrary:bintrayUpload'.
> Could not upload to 'https://api.bintray.com/content/b12kab/maven/tmdblibrary/0.11.0/tmdblibrary/tmdblibrary/unspecified/tmdblibrary-unspecified.pom': HTTP/1.1 400 Bad Request [message:Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path 'tmdblibrary/tmdblibrary/unspecified/tmdblibrary-unspecified.pom']
```
This is the error when I create the version via the website and then do the bintrayUpload:
```
Execution failed for task ':tmdblibrary:bintrayUpload'.
> Could not upload to 'https://api.bintray.com/content/b12kab/maven/tmdblibrary/0.11.0/tmdblibrary/tmdblibrary/unspecified/tmdblibrary-unspecified.pom': HTTP/1.1 400 Bad Request [message:Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path 'tmdblibrary/tmdblibrary/unspecified/tmdblibrary-unspecified.pom']

```
Any thoughts on why the version name didn't follow thru and replace the 'unspecified'?

I also looked at the filesystem to try to find the local version of the POM file, but couldn't find it. Is there a way to indicate a way to save a local copy of it?

**Comment by eyalbe4** [comment]
@b12kab,
Does your build.gradle include a *version* property, in addition to the one defined in the *pom.install* closure? If not, can you please try to add it? Do you get the same issue when using the example projects I mentioned in my previous message?

**Comment by b12kab** [comment]
Yes there is one. Take a look at the [this](jcenter-try2.gradle ) line 61. `version jcenterVersion`

I've looked at the variable before going in and it does have a value. I've also substituted a hard coded value as well. Both give the same error as noted above.

BTW - Is there a way to keep the local copies of the files before they are deleted by the bintrayUpload? Looking at the POM file before it's removed would be helpful to try to figure out what is the problem. Note: I tried publish = false in the bintray closure, but that didn't keep a local copy of POM (or the other files).

**Comment by eyalbe4** [comment]
@b12kab,
I've just looked at the gradle build script and it looks like you have configured the version in two places: inside the pom.install closure and inside the bintray closure, but it is missing outside the closures. You can use the examples as a reference. That is probably the root cause of the issue.
As for the cached files, are you referring to the jar files of the project? They should be inside the libs directory.

**Comment by b12kab** [comment]
Thanks! Getting closer, almost done. I'm now getting the below error:

`> Could not upload to 'https://api.bintray.com/content/b12kab/maven/tmdblibrary/0.11.0/tmdblibrary/tmdblibrary/0.11.0/tmdblibrary-0.11.0.pom': HTTP/1.1 400 Bad Request [message:Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path 'tmdblibrary/tmdblibrary/0.11.0/tmdblibrary-0.11.0.pom']`

A question that I have is with the upload URL 
`https://api.bintray.com/content/b12kab/maven/tmdblibrary/0.11.0/**tmdblibrary**/**tmdblibrary**/**0.11.0**/tmdblibrary-0.11.0.pom`
I don't know how Bintray upload works, but it's strange to me to repeat the "tmdblibrary" part an additional 2 times and repeat the "0.11.0" version. Is this normal?

I guessed that the aar, source, javadoc, POM files would be staged in a directory to be sent over to Bintray. I found a generated POM file, but it had a name of "./tmdblibrary/build/poms/pom-default.xml" I had guessed it would be named "tmdblibrary-(version).pom". It just looked weird to me :)

**Comment by eyalbe4** [comment]
@b12kab,
Please use the same approach you took with the version and make sure the group defined inside the pom.install closure matches the one defined outside. That should fix the issue.

**Comment by b12kab** [comment]
Hi - making that change, it now uploads works. A few remaining questions:

1. What's the best online / book to read to get better at gradle / clojure?

2. Given this upload URL, https://api.bintray.com/content/b12kab/maven/tmdblibrary/0.11.0/tmdblibrary/tmdblibrary/0.11.0/tmdblibrary-0.11.0.pom
Is the reason why it has "0.11.0/tmdblibrary/tmdblibrary/0.11.0" because the name and artifactId are both named "tmdblibrary"?

3. On Bintray, it uploaded files to 2 directories: 
/com/b12kab/tmdblibrary/tmdblibrary/0.11.0 **[it has the javadoc, source, aar and POM]**
and
/tmdblibrary/tmdblibrary/0.11.0 **[it has the javadoc, source and aar]**
This seems odd to me. Is this the normal way things are uploaded?

**Comment by DCRichards** [comment]
To clarify the issue here, for those like me who came here and spent a while figuring out the root of the problem, you need to add a top level `version "MY VERSION"` in your gradle file. For example:

```groovy
apply plugin: 'maven-publish'
apply plugin: 'com.jfrog.bintray'

// This needs to be included
version '1.0.0'

publishing {
    publications {
        Production(MavenPublication) {
        }
    }
}

bintray {

}
```

Top save repetition, you should then be able to reference `this.version` inside your closures. For example:

```groovy
publishing {
    publications {
        Production(MavenPublication) {
            version this.version
        }
    }
}
```

**Comment by b12kab** [comment]
FYI I figured out the duplication of tmdblibrary, it was my name com.b12kab.tmdblibrary + the usage of 'tmdblibrary' as the library name. I think that Bintray upload back end isn't treating it correctly and doubles it up. I end up logging into Bintray and removing the duplicate upload. Since I've not needed to do it too much, it's not that big of deal. I was curious if anyone else had this as a problem before.

In my [build.gradle ](https://github.com/b12kab/tmdblibrary/blob/master/tmdblibrary/build.gradle)file, I have a function that returns the version number, similar to what you have with the 'version' variable. 

I've got the actual work done in an additional [gradle file](https://github.com/b12kab/tmdblibrary/blob/master/gradle/bintray-upload.gradle). 

I didn't use the publications enclosure, as that didn't seem to work for me when I tried it.

The problem with how the example is setup, it doesn't allow an easy add on to those people who use Android Studio. I think that this is not your main audience, but it really doesn't work well if you alter it up with the way it's noted in the example (if it now works - it didn't when I originally tried it and I've not tried it since). Android studio's gradle then doesn't recognize it as a AS gradle project and you have to either always use gradle command line or use close to what Android studio creates. The way I've structured allows me to use Android studio w/o issue in the UI, then after completion uploading to Bintray with gradle command line.
