### ISSUE TITLE
Error:Could not find method publishing() for arguments [xxx] on project ':xxxLib' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by yilylong** [bintray/gradle-bintray-plugin#173]
Error:Could not find method publishing() for arguments [build_6lrk68fezm8opc43qo0ens894$_run_closure5@3831ef3b] on project ':channeltagviewLib' of type org.gradle.api.Project.

**Comment by eyalbe4** [comment]
@yilylong,
Can you please elaborate more on what you are trying to build? Can you share a sample project through github which reproduces this issue?

**Comment by LaurieScheepers** [comment]
What was the solution? Facing the same issue.

**Comment by lbarreraabarca** [comment]
Hi , could you share the solution ? Please.

**Comment by nigams** [comment]
Adding this in case it helps/.

The most likely reason here is your build.gradle or some .gradle file contains a "publishing" task that is not supported by the build plugin used in the project. Check if a newer version of the related gradle build plugin relevant to your project build is available and try that. You would set the version in a .gradle file.

That is a generic high-level statement. For example, so if you are using Kotlin, upgrade to a newer version of the Kotlin Gradle plugin. Likewise, if you are doing an Android build, upgrade to a newer Android Gradle version. 

Hope that helps.
