### ISSUE TITLE
PackageConfig class not accessible when using gradle kotlin-script

### ISSUE THREAD

**Issue by sbuettner** [bintray/gradle-bintray-plugin#193]
The classes that the `BintrayExtension` contains should be publicly accessible. Otherwise they are not usable from kotlin.

Here is a workaround that requires the usage of the groovy/kotlin interop like here https://github.com/gradle/kotlin-dsl/tree/master/samples/groovy-interop

Create a groovy file named `groovy.gradle` in your project: 
```
ext.bintrayPackage = { ->
    repo = "myRepoName"
    name = "myProjectName"
    userOrg = "myOrgName"
}
```

and reference it from your `build.kts`:
```
apply {
	from("groovy.gradle")
}

val bintrayPackage: groovy.lang.Closure<Any> by extra

bintray {
	user = ...
	key = ...
	pkg(bintrayPackage)
}
```

**Comment by teyckmans** [comment]
this works for me:

```
pkg(closureOf<BintrayExtension.PackageConfig>{
...
}
```

**Comment by sbuettner** [comment]
@teyckmans suggestion works in the current version `1.8.0`.
