### ISSUE TITLE
Does not support the use of api and implementation methods dependencies

### ISSUE THREAD

**Issue by JessYanCoding** [bintray/gradle-bintray-plugin#197]
Hi, i use the api and implementation methods to depend on the three-party library, But after uploading to bintray found that the .pom file does not have a three-party library, the compile method is deprecated on [Android-Gradle-Plugin v3.0](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations)

**Comment by gelldur** [comment]
Solution is to move back from `api` -> `compile`

**Comment by JessYanCoding** [comment]
@gelldur thx

**Comment by d4rken** [comment]
Any update on this?

**Comment by d4rken** [comment]
FYI: I fixed this by updating my use of [android-maven-gradle-plugin](https://github.com/dcendents/android-maven-gradle-plugin) from `1.5` to `2.1`.
