### ISSUE TITLE
Build successful; but jar file seems missing on jcenter

### ISSUE THREAD

**Issue by jillesvangurp** [bintray/gradle-bintray-plugin#209]
I've been trying to release a simple OSS java library (single jar file) with the following gradle file:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
    }
}

plugins {
    id "com.jfrog.bintray" version "1.8.0"
}

apply plugin: 'maven-publish'

group 'io.inbot'
version '0.1.0'

ext.isReleaseVersion = false

apply plugin: 'java'

jar {
    baseName = 'inbot-eth-contracts'
}

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile ('org.web3j:core:3.2.0')
}

ext.pgpPassword='XXXXX'
ext.jcenterApiKey='XXXXX'

task sourceJar(type: Jar) {
    from sourceSets.main.allJava
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
//
//            artifact sourceJar {
//                classifier "sources"
//            }
        }
    }
}

// deploy using gradle -PjcenterApiKey=XXXXXXX -PpgpPassword=XXXXXXX clean bintrayUpload
bintray {
    user = 'jillesvangurp'
    key = jcenterApiKey
    publications = ['mavenJava']
    dryRun = false //[Default: false] Whether to run this as dry-run, without deploying
    publish = true //[Default: false] Whether version should be auto published after an upload
    override = false //[Default: false] Whether to override version artifacts already published
    pkg {
        repo = 'inbot-maven-repo'
        name = 'inbot-eth-contracts'
        userOrg = 'inbot'
        licenses = ['MIT']
        vcsUrl = 'https://github.com/Inbot/inbot-eth-contracts.git'
        websiteUrl = 'https://github.com/Inbot/inbot-eth-contracts'
        githubRepo = 'Inbot/inbot-eth-contracts'
        version {
            name = '0.1.0' //Bintray logical version name
            desc = //Optional - Version-specific description'
            vcsTag = 'v0.1.0'
            gpg {
                sign = true //Determines whether to GPG sign the files. The default is false
                passphrase = pgpPassword //Optional. The passphrase for GPG signing'
            }
        }
    }
}
```

I uploaded with the following commands.

```
gradle -PjcenterApiKey=XXXXXX -PpgpPassword=XXXXXX bintrayUpload --debug
```

This errored several times due to apparent server failures and timeouts (website is extremely slow) before it finally succeeded. I got a 405 at some point and a weird html error when it timed out. Because of these failures I had debug logging turned on when it finally 'succeeded'. 

Here's the gradle debug log; note it uploads both the pom and the signed jar successfully (201 created for the jar file).
https://gist.github.com/jillesvangurp/cda822a2a4b9905a96a38b57b531914e

However, while I can find the package and version on jcenter, there is no sign of the jar file. I have no idea how to fix this or what is wrong. The plugin is basically telling me everything succeeded even though I can see this is clearly not the case. It's not helpful that the website is extremely unresponsive.

Is this going to be eventually consistent or should I just delete the version and try again?

**Comment by TonnyL** [comment]
Hi, @jillesvangurp 
I got the same issue, do you have any solutions?

**Comment by jillesvangurp** [comment]
Looked like they had some server issues; the slowness was a good hint that something was up. The problem went away eventually. I wasted a good amount of time on publishing a simple small jar file and failing repeatedly.  Given the problems I've had with it, I won't be going near jcenter any time soon.

**Comment by jamesbassett** [comment]
Looks like I've run into the same issue. I attempted to publish 2 different projects with the exact same gradle config - the first one uploaded successfully and all artifacts are available via jcenter, and the second one uploaded successfully (according to the gradle plugin) but:

- the files aren't visible in bintray (they were initially visible under the files tab, but not in the versions section on the general tab....but now they've disappeared altogether!)
- they seem to exist, as I can't republish with the same maven coordinates (HTTP/1.1 409 Conflict [message:Unable to upload files....already exists)
- if I try to download the file from the repo I get a basic auth popup (if i do this for an older version it works fine)

I've fired off a support email but not sure how long that will take to get looked at. I'm not sure if I should try and create a new version - if that fails as well I'll be in an even worse place :(

I'll give it a few hours and see......

**Comment by jamesbassett** [comment]
Ok, it didn't resolve itself, but I've 'fixed it'. I just enabled override in the bintray plugin and republished. It took a really long time (over 10 min) as Bintray's servers were in a degraded state ("Slowness with the REST API, UI and Downloads") but it eventually republished and my files are available in Jcenter now. Not a huge amount of faith in bintray right now...

**Comment by eyalbe4** [comment]
I'm closing this issue for now.
Do let us know if you think there's something we can add or change in the plugin side.
Thanks

**Comment by rashad-farajullayev** [comment]
Same problem in my case. artifact is deployed to bintray. Through web interface I can see this is there. 
But, cannot download and use it in another project. Says, the artifact is missing

**Comment by fedup41** [comment]
Same problem here for 4 projects I just added.  I can get the pom files but nothing else when I reference them as dependencies in another project.

**Comment by jillesvangurp** [comment]
I stopped using jcenter due to repeated outages, flakiness, and the stuff outlined above. I recommend using jitpack.io for stuff that doesn't need to be on maven central and using sonatype OSS when you do need maven central. 

Jitpack is awesome. All you need to do there is git tag your releases on github. It builds them straight from source. Super fast and jars are available in seconds. This is exactly how this stuff should work. Simple, fast, easy. The exact opposite of either Jcenter or Sonatype.
