### ISSUE TITLE
Failed to resolve - after successful bintrayUpload

### ISSUE THREAD

**Issue by Faltenreich** [bintray/gradle-bintray-plugin#217]
Dear Bintray-team,

thank you very much for accepting my request to include my package to JCenter. It is much appreciated!

Sadly I am currently struggling with publishing the linked package: faltenreich/maven/TextInputView.

I have uploaded my Android library to bintray using this guide: 
https://notes.devlabs.bg/beginners-guide-for-publishing-a-kotlin-library-to-jcenter-41272bfc214

gradlew install and gradlew bintrayUpload both succeed and the file structure of the package on bintray.com seems okay. 
Unfortunately I am not able to download the library via Gradle. 

I have added the library like advised in the bintray build settings: 
`implementation "com.faltenreich:textinputview:1.0.0"`

Gradly sync fails with the following message:
`Error:Failed to resolve: com.faltenreich:textinputview:1.0.0`

I am using the following dependencies for the bintrayUpload:

```
classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.0'
classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'
classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.16"
```

You can find the complete sourcecode on Github:
https://github.com/Faltenreich/TextInputView/tree/develop

I would highly appreciate if you could help me fixing this problem.

Thanks in advance and best regards,
Philipp

**Comment by Faltenreich** [comment]
I will answer this question by myself, since I resolved the problem with help of the JFrog support.

Something went wrong on linking my package with JCenter, so the path structure did not match what I expected. The solution was to relink the package which needs to be done by the Bintray / JCenter / JFrog support.

**Comment by Papashkin** [comment]
> I will answer this question by myself, since I resolved the problem with help of the JFrog support.
> 
> Something went wrong on linking my package with JCenter, so the path structure did not match what I expected. The solution was to relink the package which needs to be done by the Bintray / JCenter / JFrog support.

Do you use the `Enterprise (trial)` account on Bintray or `Premium`?

**Comment by forntoh** [comment]
> I will answer this question by myself, since I resolved the problem with help of the JFrog support.
> 
> Something went wrong on linking my package with JCenter, so the path structure did not match what I expected. The solution was to relink the package which needs to be done by the Bintray / JCenter / JFrog support.

I have the same problem, how do I solve this, I don't see any link to contact support
