### ISSUE TITLE
Upload Uri Interpolation Problem on Gradle 4.8

### ISSUE THREAD

**Issue by sghill** [bintray/gradle-bintray-plugin#234]
Hello,

While running on Gradle 4.8-rc-2, I noticed the upload uri is being constructed incorrectly:

> Could not upload to 'https://api.bintray.com/content/nebula/gradle-plugins/gradle-ospackage-plugin/4.9.0-rc.2/value: com/netflix/nebula/value: gradle-ospackage-plugin/value: 4.9.0-rc.2/value: gradle-ospackage-plugin-value: 4.9.0-rc.2.pom'

I debugged this locally and found that an internal api is being used at [BintrayUploadTask.groovy#634](https://github.com/bintray/gradle-bintray-plugin/blob/master/src/main/groovy/com/jfrog/bintray/gradle/BintrayUploadTask.groovy#L634). This api used to return the groupId, artifactId, and version attributes as a String, but it is now `org.gradle.api.provider.Property<String>`.

Fortunately, groupId, artifactId, and version are all available on the public [`MavenPublication`](https://docs.gradle.org/current/javadoc/org/gradle/api/publish/maven/MavenPublication.html) interface as Strings, so this can be fixed in a backwards-compatible way.

See also JFrogDev/build-info#166.

**Comment by emkidwell** [comment]
Update from JFrog: 

"We are currently investigating this issue and will get back to you shortly (tomorrow at the latest).

Best regards,
Marc Bui"

**Comment by sghill** [comment]
Here's a build.gradle that reproduces this problem:

```
plugins {
  id 'java'
  id 'maven-publish'
  id 'com.jfrog.bintray' version '1.8.0'
}

group = 'com.example'
version = '0.1.0'

publishing {
  publications {
    ourPublication(MavenPublication) {
      from components.java
    }
  }
}

bintray {
  user = 'none'
  key = 'none'
  publications = ['ourPublication']
  pkg {
    repo = 'generic'
    name = 'example'
    licenses = []
    vcsUrl = 'https://github.com/sghill/bintray-example.git'
  }
  dryRun = true
}
```
settings.gradle:
```
enableFeaturePreview('STABLE_PUBLISHING')
rootProject.name='example-project'
```

The output:
```
> Task :bintrayUpload
Caching disabled for task ':bintrayUpload': Caching has not been enabled for the task
Task ':bintrayUpload' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Gradle Bintray Plugin version: 1.8.0
Package 'example' does not exist. Attempting to create it...
(Dry run) Created package 'none/generic/example'.
Version 'none/generic/example/0.1.0' does not exist. Attempting to create it...
(Dry run) Created version 'none/generic/example/0.1.0'.
Uploading to https://api.bintray.com/content/none/generic/example/0.1.0/value: com/example/value: example-project/value: 0.1.0/value: example-project-value: 0.1.0.jar...
(Dry run) Uploaded to 'https://api.bintray.com/content/none/generic/example/0.1.0/value: com/example/value: example-project/value: 0.1.0/value: example-project-value: 0.1.0.jar'.
Uploading to https://api.bintray.com/content/none/generic/example/0.1.0/value: com/example/value: example-project/value: 0.1.0/value: example-project-value: 0.1.0.pom...
(Dry run) Uploaded to 'https://api.bintray.com/content/none/generic/example/0.1.0/value: com/example/value: example-project/value: 0.1.0/value: example-project-value: 0.1.0.pom'.
:bintrayUpload (Thread[Task worker for ':',5,main]) completed. Took 1 mins 2.382 secs.
```

I think a change like [this one](https://github.com/bintray/gradle-bintray-plugin/compare/master...sghill:4.8-compat#diff-0923d2ba361d9c727a2534cf6c6b3f99) would move to public apis and just work.

**Comment by tiurikov** [comment]
Hey there! Any updates from JFrog team? Looks like a blocker for everyone who releases using gradle-bintray-plugin and gradle 4.8.

**Comment by eyalbe4** [comment]
@tiurikov and @emkidwell,
We're currently working on the compatibility fix. 
We will release a fix by the end of the week (hopefully sooner).

**Comment by warnyul** [comment]
I tested with my android-maven-publish plugin. I created a release with Gradle 4.8 and bintray 1.8.1 a few hours ago

**Comment by tiurikov** [comment]
@AlexeiVainshtein, it works well for me! Thank for the fix!
