### ISSUE TITLE
Package names ending with `-test` aren't able to upload

### ISSUE THREAD

**Issue by StefMa** [bintray/gradle-bintray-plugin#249]
Hey guys 👋 

I try to upload a package with the name `-test`.
Unfortunately it isn't possible.
I always get the error:
> Repository name, package name or version name are null for project: project ':project-name-test'

If I rename the package to something else than `-test` it will publish successfully (without changing my configuration of course).

I've also debugged the output of the `version`, the `repo` and the `name` and all where set correctly in the `bintray` block:
```
    println bintray.pkg.version.name
    println bintray.pkg.repo
    println bintray.pkg.name
```

**Comment by StefMa** [comment]
The issue was **no** the because of the `-test` package.
It was because my plugin (which applies this plugin) do it inside a `project.afterEvaluate`-listener.
Which leads to the fact that the `ProjectsEvaluatedBuildListener#afterEvaluate` wasn't called.
Which means the `bintrayUploadTasks`-List will *never* add the `bintrayUpload` to the list.
Which leads to the fact that the `ProjectsEvaluatedBuildListener#projectsEvaluated` iterates over an empty list. The task will never be setup correctly...

**Comment by fardavide** [comment]
@StefMa any solution in case the plugin must be setup only inside an afterEvaluate block?
