### ISSUE TITLE
Artifact path broken using >= Gradle 4.9

### ISSUE THREAD

**Issue by tobiasheine** [bintray/gradle-bintray-plugin#253]
When the consumer project uses Gradle 4.9 or 4.10, the artifact path is resolved wrong.

What we can see in the log:
```
Uploading to https://api.bintray.com/content/foo/generic/gradle-bintray-plugin-example/1.0-Final/property(class java/lang/String, fixed(class java/lang/String, org/jfrog/example/gradle))/property(class java.lang.String, fixed(class java.lang.String, gradle-bintray-plugin-example))/property(class java.lang.String, fixed(class java.lang.String, 1.0))/property(class java.lang.String, fixed(class java.lang.String, gradle-bintray-plugin-example))-property(class java.lang.String, fixed(class java.lang.String, 1.0)).jar...
```

How it should look like:
```
Uploading to https://api.bintray.com/content/foo/generic/gradle-bintray-plugin-example/1.0-Final/org/jfrog/example/gradle/gradle-bintray-plugin-example/1.0/gradle-bintray-plugin-example-1.0.jar...
```

This can be reproduced using the official [publications-example](https://github.com/bintray/bintray-examples/tree/master/gradle-bintray-plugin-examples/publications-example). Just bump the Gradle Version to 4.9 and run `bintrayUpload -PbintrayUser=foo -PbintrayApiKey=bar` which will prompt the broken path.

**Comment by mr-archano** [comment]
It seems like the issue is gone in recent versions of the plugin (1.8.1+).

**Comment by eyalbe4** [comment]
Thanks for the update @mr-archano!

**Comment by Steppschuh** [comment]
I'm facing the same issue with gradle version 4.10.1 and `build-info-extractor-gradle` version 4.8.1.
