### ISSUE TITLE
Execution failed for task ':bintrayUpload'. > Cannot get property 'rootProject' on null object

### ISSUE THREAD

**Issue by electronstudio** [bintray/gradle-bintray-plugin#269]
Same problem as #252 .  Downgrading to 1.8.1 is a workaround, not a fix, so issue should not be closed.

**Comment by pmcneil** [comment]
Do youhave a settings.gradle file with `rootProject.name = 'blah' ?

**Comment by electronstudio** [comment]
seems to be working in 1.8.4
