### ISSUE TITLE
Wrong docs for new Gradle system with Android

### ISSUE THREAD

**Issue by VedavyasBhat** [bintray/gradle-bintray-plugin#274]
To package an Android library, the POM file doesn't include dependencies, so a manual override to the  POM must be made. Step 4 of the docs [here](https://github.com/bintray/gradle-bintray-plugin#Getting_Started_Using_the_Plugin) covers that, but there is an error in the following block:

```
    pom.withXml {
        // Iterate over the compile dependencies (we don't want the test ones), adding a <dependency> node for each
        configurations.implementation.allDependencies.each {
           // Ensure dependencies such as fileTree are not included.
           if (it.name != 'unspecified') {
              def dependencyNode = dependenciesNode.appendNode('dependency')
              dependencyNode.appendNode('groupId', it.group)
              dependencyNode.appendNode('artifactId', it.name)
              dependencyNode.appendNode('version', it.version)
           }
        }
      }
```

In the `implementation` (and `api`, for that matter) configuration, there is no `dependenciesNode` variable; it needs to be defined. Here is the above block with the fix (code tested and POM verified):

```
    pom.withXml {
        def dependenciesNode = asNode().getAt('dependencies')[0] ?: asNode().appendNode('dependencies')
        // Iterate over the compile dependencies (we don't want the test ones), adding a <dependency> node for each
        configurations.implementation.allDependencies.each {
           // Ensure dependencies such as fileTree are not included.
           if (it.name != 'unspecified') {
              def dependencyNode = dependenciesNode.appendNode('dependency')
              dependencyNode.appendNode('groupId', it.group)
              dependencyNode.appendNode('artifactId', it.name)
              dependencyNode.appendNode('version', it.version)
           }
        }
      }
```

**Comment by langsmith** [comment]
+1 about the error existing and the code to fix it. I ran into the issue mentioned above and in https://github.com/bintray/gradle-bintray-plugin/issues/272. @VedavyasBhat 's code above got rid of it 🚀

**Comment by eyalbe4** [comment]
Thank you @VedavyasBhat and @langsmith for pointing this out!
Would one of you be willing to create a pull request to fix this?

**Comment by VedavyasBhat** [comment]
Sure, I'll have one up shortly.

**Comment by langsmith** [comment]
Cool, thanks @VedavyasBhat

**Comment by olLenz** [comment]
The gradle sync fails when using the code snipped with the error:
`Gradle DSL method not found: 'asNode()'`

After moving the line `def dependenciesNode = asNode().getAt('dependencies')[0] ?: asNode().appendNode('dependencies')` into the `pom.withXML {}`-scope the gradle sync was successfull. This should be updated in the docs :)
