### ISSUE TITLE
bintrayUpload Repository name, package name or version name are null for project

### ISSUE THREAD

**Issue by gyosida** [bintray/gradle-bintray-plugin#281]
I upgraded the Bintray plugin to the latest version `1.8.4` and the bintrayUpload task started to fail, printing the warning:
`Repository name, package name or version name are null for project`
why would some of those variables be null? Something weird is that the script could successfully upload and publish 17 previous aar.

Just let me know if you need any other input from me to track this down. Thanks.

**Comment by suchoX** [comment]
Do you have `apply plugin: 'com.jfrog.bintray` in your root `build.gradle` file? if yes, then remove it. Apply the plugin only in the libraries that you want to upload.

**Comment by yaroslav-orel** [comment]
@gyosida  Have you resolved the issue? I'm facing the same one. Please adivse

**Comment by iFr0z** [comment]
@suchoX Bro! Big thx!!! You save my time and life :)
