### ISSUE TITLE
com.github.username groupID not allowed for JCenter

### ISSUE THREAD

**Issue by tschoonj** [bintray/gradle-bintray-plugin#297]
After successfully using this plugin to upload my artifacts to my Bintray maven repository, I put in a request to include them also in the JCenter repo.

This request was denied with the following message:

> Hi tschoonj,
> 
> Thank you for submitting the request.
> 
> We see that you have requested to add the path " com/github/tschoonj/xraylib ". However, provide us a proof that you are an employee of the Github organisation since you want to use com/github in your path prefix. GitHub, as an organisation uses the path " com/github " and only an employee or member of that organisation can use that group ID.
> 
> If you are not associated with Github organisation, please update the package path accordingly so that we can verify your request.
> 
> 
> Best regards,
> JFrog Support 

Obviously, I am not an employee of the GitHub organization, just a long-time user.

This reply strikes me as odd as this seems to be a very commonly used convention for picking groupIDs. There are also numerous examples on JCenter where such groupIDs were accepted.

Pointing this out was disregarded by JFrog support.

I would be grateful if someone could look into this.

**Comment by iFr0z** [comment]
@tschoonj hello! _JCenter_ **does not register GROUP_ID**, but only gives approval for publication.

---

**Register GROUP_ID** with _Sonatype_

_Sonatype OSS Repository Hosting Service_ is a trusted artifact repository for Maven Central. Maven Central servers are regularly synchronized with OSSRH, and those artifacts that the user marks as ready for release are uploaded to the Maven Central central repository. To register GROUP_ID, on behalf of which you will distribute libraries, you need to enter issue in their JIRA. After reviewing the application, you will open the desired repository on Sonatype, and you can download the artifact.

Register [here](https://issues.sonatype.org), open and fill out a new issue:

![f56edce729c146acb64ce718f59f425b](https://user-images.githubusercontent.com/4560636/64400400-50c0df80-d096-11e9-81e0-12ef2c877883.png)

![35529d9be48f4f61bdb3a44f9f766e70](https://user-images.githubusercontent.com/4560636/64400409-59b1b100-d096-11e9-9bd1-32eb416aa83c.png)

It remains to wait for an answer, after which you will be created by Sonatype repositories with the selected GROUP_ID. They answered me within an hour:

![de70d9b352f34c3ab8d0b84261941e41](https://user-images.githubusercontent.com/4560636/64400436-7221cb80-d096-11e9-924b-8e65195b3773.png)

And it will also be necessary to prove that it is you who own your account on GitHub:

![image](https://user-images.githubusercontent.com/4560636/64400608-36d3cc80-d097-11e9-926b-5d34184bd53c.png)

We only need to connect our Sonatype account with Bintray, for this we go to Profile Settings -> Accounts and specify the username that was registered in the Sonatype dir:

![ffef4dd0536d4fc8b7ea39fb69c8208a](https://user-images.githubusercontent.com/4560636/64400449-849c0500-d096-11e9-8c59-ece489d8d460.png)

---

[Source](https://habr.com/ru/post/266801/)

**Comment by tschoonj** [comment]
This was not about getting the jars on MavenCentral, just on JCenter.

Anyway, a couple of hours after posting this issue, JFrog customer support saw the error of their ways, and allowed me to publish on JCenter after all...
