### ISSUE TITLE
Received status code 405 from server: Method Not Allowed

### ISSUE THREAD

**Issue by alshan** [bintray/gradle-bintray-plugin#310]
Hi, I started to receive failures when trying to publish to maven repo at bintray:
```
> Failed to publish publication 'my publication' to repository 'maven'
   > Could not PUT 'https://my-bintray-maven-repo/group-id/artifact-id/1.1.2-SNAPSHOT/maven-metadata.xml'. Received status code 405 from server: Method Not Allowed
``` 
The same gradle configuration has been working just fine (the last time about month ago). I've checked permissions and everything else I can think of but could not see any issues on my side.

I wonder is that possible that bintray has migrated to an artifactory version which is not fully compatible with gradle-bintray plugin v. 1.8.4 ? Did anybody else experience similar issues lately?
Thank you.

**Comment by Andre601** [comment]
I don't have this issue.
I use Gradle 5.5 with this plugin being 1.8.4 (latest).

What is your actual setup?
`405 Method Not Allowed` already gives the hint that you seem to use a method which is unsupported.

**Comment by alshan** [comment]
Andre, never mind, gradle bintray plugin works great! I've found the problem - it was my mistake.

**Comment by twoversionsofme** [comment]
> Andre, never mind, gradle bintray plugin works great! I've found the problem - it was my mistake.

I'm running into the same issue currently.  Any hints as to how you fixed it would be helpful.
