### ISSUE TITLE
It says it was uploaded but directory is empty...

### ISSUE THREAD

**Issue by deanorderly** [bintray/gradle-bintray-plugin#312]
I see this in the logs

Uploaded to 'https://api.bintray.com/content/deanhiller/maven/webserver/2.0.18/org/webpieces/webserver/2.0.18/webserver-2.0.18.jar'.
Uploading to https://api.bintray.com/content/deanhiller/maven/webserver/2.0.18/org/webpieces/webserver/2.0.18/webserver-2.0.18.pom...
Uploaded to 'https://api.bintray.com/content/deanhiller/maven/webserver/2.0.18/org/webpieces/webserver/2.0.18/webserver-2.0.18.pom'.

BUT when in chrome I go to the URL 
https://api.bintray.com/content/deanhiller/maven/webserver/2.0.18/org/webpieces/webserver/2.0.18

the directory is empty?  Why is it saying it uploaded it there when there is nothing there?

**Comment by deanorderly** [comment]
oh, not to mention, that is the wrong package actually.  the package I see in the pom.xml file is
  <groupId>org.webpieces</groupId>

and yet it is putting it at org/webpieces/webserver/2.0.18 . (That webserver should not be there..why is the groupId from the pom not being used?

**Comment by deanorderly** [comment]
In case it helps, this is our evaluate bin tray branch's build.gradle file https://github.com/deanhiller/webpieces/blob/evaluateBintray/build.gradle

We are evaluating bintray for open source and for internal use right now but I got stuck on this so could not continue the evaluation.

**Comment by deanorderly** [comment]
(currently, you can see the commented out code of sonatype ;) ).

**Comment by GlennRicaud** [comment]
Same behaviour here. The plugin stopped to work.
I tried with an old version of an artifact that I had uploaded successfully before. Same Java/Gradle/Plugin/... versions, I get the same behaviour:

```
> Task :bintrayUpload
Uploading to https://api.bintray.com/content/rcd-systems/rcd-repo/datatoolbox/2.2.6-TESTUPLOAD/systems/rcd/enonic/datatoolbox/2.2.6-TESTUPLOAD/datatoolbox-2.2.6-TESTUPLOAD.jar...
Uploaded to 'https://api.bintray.com/content/rcd-systems/rcd-repo/datatoolbox/2.2.6-TESTUPLOAD/systems/rcd/enonic/datatoolbox/2.2.6-TESTUPLOAD/datatoolbox-2.2.6-TESTUPLOAD.jar'.
```

I get an empty directory as mentioned above (An empty directory was created, but no artifact uploaded).

My other softwares with Maven build seem fine. So I guess it is due to a recent incompatibility between the API and the plugin?

**Comment by deanorderly** [comment]
yeah, I figured that out.  I need to close this..oops.
