### ISSUE TITLE
'com.jfrog.bintray.gradle.tasks.BintrayUploadTask_Decorated' to class 'com.jfrog.bintray.gradle.tasks.BintrayUploadTask'

### ISSUE THREAD

**Issue by GuilhE** [bintray/gradle-bintray-plugin#328]
This build.gradle (project) setup fails:

```
plugins {
    id "maven-publish"
    id "com.jfrog.bintray" version "1.8.5"
}
```

> 1: Task failed with an exception.
> -----------
> * What went wrong:
> Execution failed for task ':module:bintrayUpload'.
> > Cannot cast object 'task ':bintrayUpload'' with class 'com.jfrog.bintray.gradle.tasks.BintrayUploadTask_Decorated' to class 'com.jfrog.bintray.gradle.tasks.BintrayUploadTask'
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> ==============================================================================
> 
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> Execution failed for task ':bintrayPublish'.
> > Cannot cast object 'task ':module:bintrayUpload'' with class 'com.jfrog.bintray.gradle.tasks.BintrayUploadTask_Decorated' to class 'com.jfrog.bintray.gradle.tasks.BintrayUploadTask'

This works: 

```
dependencies {
        classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.5"
}

plugins {
    id "maven-publish"
    //id "com.jfrog.bintray" version "1.8.5"
}
```

Why? 🤔

**Comment by dubinsky** [comment]
@GuilhE this looks like a class-loader issue; if you have multiple subprojects in your Gradle project,
[this](http://dub.podval.org/2020/06/29/bintray-gradle-plugin.html) *may* help...
