### ISSUE TITLE
Generic repository support

### ISSUE THREAD

**Issue by marcote** [bintray/gradle-bintray-plugin#43]
Maven deployment works fine, but I'm unable to find a way to upload binaries into a Generic repository.
Thanks,

**Comment by sebersole** [comment]
I have not tried yet, but I believe that is the purpose of the `filesSpec` option within the extension.  Have you tried that?

**Comment by marcote** [comment]
To be complete honest, I have no idea what I did as a workaround. I'm closing this.
Thanks
