### ISSUE TITLE
v1.1 not available on https://plugins.gradle.org

### ISSUE THREAD

**Issue by Petikoch** [bintray/gradle-bintray-plugin#58]
Hi guys,

thanks for the 1.1 release.

Wenn will it be available on https://plugins.gradle.org/plugin/com.jfrog.bintray?

Best regards,
Peti

**Comment by jbaruch** [comment]
[The package is linked to the gradle-plugins repo](https://bintray.com/gradle/gradle-plugins?filterByPkgName=gradle-bintray-plugin), so it must be something with the sync of the portal.

**Comment by alkemist** [comment]
Most expedient thing to do would be to ask a message to the Gradle org on Bintray. We have a better process for dealing with this there.

**Comment by jbaruch** [comment]
Done, thanks!

**Comment by bigdaz** [comment]
Looks like v1.1 is missing the 'gradle-plugin' attribute:
https://bintray.com/jfrog/jfrog-jars/gradle-bintray-plugin/1.1/view

Compare with:
https://bintray.com/jfrog/jfrog-jars/gradle-bintray-plugin/1.0/view

**Comment by jbaruch** [comment]
OMG, what a fail. Sorry!
cc @eyalbe4 @liorhson

**Comment by eyalbe4** [comment]
The property has been added to version 1.1.
We'll make sure this does not happen in the future.
Our apologies!

**Comment by Petikoch** [comment]
Works now... thanks!
