### ISSUE TITLE
Allow upload of latest version to already created bintray package

### ISSUE THREAD

**Issue by doridori** [bintray/gradle-bintray-plugin#67]
Hi, 

I have created a package on bintray already - but it seems that the gradle plugin requires that I enter all the package config info (i.e. Licences etc) here as well. Am I missing something? I expected I would need to add my bintray user pass and the bintray package id/name and then the `bintrayUpload` task would 

- build 
- create pom including gradle 
- dependencies 
- sign
- upload

Am I missing the config that allows you to not enter the duplicate information? 

Also the bintray block requires the version name to be entered which is also already in the gradle file?

Thx

EDIT: ah i see the package creation is optional

**Comment by eyalbe4** [comment]
Hi Dorian,
You don't have to specify all of the plugin configuration if it already exists in Bintray.
The plugin code checks if the package exists already and only if does not exist, it will use the data (the licenses for example) to create the package.
I used the below closure, first with the lines uncommitted to create the package, and then commented them to upload a new version and it worked:

bintray {
    user = bintrayUser
    key = bintrayKey
    publications = ['mavenJava']
    pkg {
        repo = repoName
        name = pkgName
//        desc =  pkgDesc
//        labels = pkgLabels
//        licenses = ['Apache-2.0']
//        websiteUrl = 'https://github.com/bintray/gradle-bintray-plugin'
//        issueTrackerUrl = 'https://github.com/bintray/gradle-bintray-plugin/issues'
//        vcsUrl = 'https://github.com/bintray/gradle-bintray-plugin.git'
        version {
            name = versionName
        }
    }
}

**Comment by doridori** [comment]
Thats great thanks :) Would be good if this was reflected in the docs as was not clear, to me at least!

**Comment by eyalbe4** [comment]
Thanks for the feedback.
Added the below comment in the example before the pkg closure.

'''groovy
//Package configuration. The plugin will use the repo and name properties to check if the package already exists. In that case, there's no need to configure the other package properties (like userOrg, desc, etc).
    pkg {
        repo = 'myrepo'
        name = 'mypkg'
...
'''
