### ISSUE TITLE
Upload release bundles created by the distributions plugin?

### ISSUE THREAD

**Issue by sebersole** [bintray/gradle-bintray-plugin#85]
Again, I might just be missing this in the readme...

I have the following config in an attempt to have the plugin upload the zip/tgz generated from the Gradle distributions plugin to a BinTray 'generic' repo:

```
bintray {
    user = binTrayUser
    key = binTrayApiKey

    publish = true

    filesSpec {
        from "$buildDir/distributions"
        into '/'
    }

    pkg {
        userOrg = 'hibernate'
        repo = 'bundles'
        name = 'hibernate-orm'
    }
}
```

The build completes fine.  The version is created under the proper BinTray package.  However, no files are uploaded.  I had to manually upload them via the BinTray web UI.  

"$buildDir/distributions" is the correct location (where distributions plugin creates the zip/tgz).  What am I missing?

**Comment by eyalbe4** [comment]
To troubleshoot your issue, you can try to build the "filesSpec-example" available here:
https://github.com/bintray/bintray-examples/tree/master/gradle-bintray-plugin-examples
Just configure your Bintray details in the build.gradle and 
run> gradle build bintrayUpload

**Comment by sebersole** [comment]
I only updated the user/key lines and get this:

````
[sebersole@t540 filesSpec-example] $ ./gradlew build bintrayUpload
...
:_bintrayRecordingCopy

FAILURE: Build failed with an exception.

* What went wrong:
Could not list contents of directory '/sys/fs/fuse/connections/42' as it is not readable.
````

No idea where `/sys/fs/fuse/connections/42` comes from...

**Comment by sebersole** [comment]
Any thoughts?

**Comment by eyalbe4** [comment]
/sys/fs is a virtual file system provided by the OS kernel. It is most unlikely that the failure to list the content of the /sys/fs/fuse/connections/42 is not directly related to the gradle plugin.

**Comment by sebersole** [comment]
Too many negatives in your last comment :)  Are you saying you do not think this is a problem in the plugin?

I don't see how it is not.

**Comment by sebersole** [comment]
Clearly this report is going nowhere and I have since chosen to not publish Hibernate's distributions to Bin Tray - so no longer a concern for me
