### ISSUE TITLE
Uploading gets 401 unauthorized for everything I haven't made by hand in the web UI

### ISSUE THREAD

**Issue by marshallpierce** [bintray/gradle-bintray-plugin#86]
I'm trying to get https://github.com/bintray/bintray-examples/tree/master/gradle-bintray-plugin-examples/configurations-example working, but after configuring my user and api key I get this for the bintrayUpload task:

```
> Could not create package 'marshallpierce/generic/gradle-bintray-plugin-conf-example': HTTP/1.1 401 Unauthorized [message:This resource requires authentication]
```

I also get the same when trying to get uploading working in https://github.com/palominolabs/metrics-new-relic/blob/bintray/build.gradle. In fact, in this project I got a 401 on the project until I made that by hand in the web UI. I got a 401 on the version until I made that by hand. Now, I get a 401 when uploading a jar.

What am I doing wrong?

**Comment by eyalbe4** [comment]
We have just improved the examples and the documentation to make it easier to properly configure and run the example projects. Before the change, you had to configure the your Bintray credentials as environment variables. Now you can either configure them as environment variables or as project properties. Please have a look at the new README file and make sure you pull the latest version of the examples.

**Comment by eyalbe4** [comment]
The examples (and the new examples documentation) is available here:
https://github.com/bintray/bintray-examples/tree/master/gradle-bintray-plugin-examples

**Comment by marshallpierce** [comment]
I'd actually already modified the build.gradle to use gradle properties anyway, but even with the updated one (now with no changes needed to build.gradle), I still get 401.

**Comment by marshallpierce** [comment]
A couple things -- the recent change to authentication is *almost* correct: the positive case in the ternary should use `rootProject.property()` not `rootProject.hasProperty()` again. 

But, more importantly, I found what was wrong in my setup! There was a trailing gremlin character in my gradle.properties from my copy-and-paste from the website for the api key. Now everything works. Whew! :)

**Comment by eyalbe4** [comment]
Great @marshallpierce !
I implemented the "property()" change as you suggested.
Thanks for helping us improve the examples.

**Comment by buildemloy** [comment]
i am getting below error every time
Execution failed for task ':empass_sdk:bintrayUpload'.
> Could not create version '1.0': HTTP/1.1 401 Unauthorized [message:This resource requires authentication]
 and use step for implement https://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en

**Comment by tarasantoshchuk** [comment]
Encountered the same problem as @buildemloy, using the same article

**Comment by buildemloy** [comment]
### Do not reply below this line ###

---------------------------------------------------------------------------------
Team Empass | November 05, 2016 | 11:32 -0700
---------------------------------------------------------------------------------

Thank you for writing in to us at Empass. Your query will be responded to soon.

Best regards,
Team Empass

**Comment by eyalbe4** [comment]
@buildemloy and @tarasantoshchuk,
If you share a sample project that shows this error, we could help troubleshoot this.

**Comment by buildemloy** [comment]
### Do not reply below this line ###

---------------------------------------------------------------------------------
Team Empass | November 05, 2016 | 15:48 -0700
---------------------------------------------------------------------------------

Thank you for writing in to us at Empass. Your query will be responded to soon.

Best regards,
Team Empass

**Comment by tarasantoshchuk** [comment]
@eyalbe4 
here is link to bintray repo: https://bintray.com/t-a/Android/native-rebound
here is link to project repo on github: https://github.com/tarasantoshchuk/NativeRebound

In last [commit](https://github.com/tarasantoshchuk/NativeRebound/commit/e1727157ae517a870e42670187983151e3f1098f) I added changes suggested in [this](https://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en) article.

But when I run "gradlew bintrayUpload" I get 

Execution failed for task ':lib:bintrayUpload'.
Could not create version '0.1.0': HTTP/1.1 401 Unauthorized [message:This resource requires authentication]

**Comment by buildemloy** [comment]
### Do not reply below this line ###

---------------------------------------------------------------------------------
Team Empass | November 06, 2016 | 08:46 -0800
---------------------------------------------------------------------------------

Thank you for writing in to us at Empass. Your query will be responded to soon.

Best regards,
Team Empass
