### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by johnjohndoe** [bintray/gradle-bintray-plugin#91]
Please consider providing a textual **changelog** so it is easier for users and developers to see what changes from version to version.
- [Example changelog of devise](https://github.com/plataformatec/devise/blob/v3.1.1/CHANGELOG.md)
- [Example changelog of cancan](https://github.com/ryanb/cancan/blob/1.6.10/CHANGELOG.rdoc)
- [Example changelog of angular.js](https://github.com/angular/angular.js/blob/v1.1.5/CHANGELOG.md)
- [GitHub offers release notes](https://github.com/jeffkreeftmeijer/fuubar/releases/new)
- [GitHub release notes example of better_errors](https://github.com/charliesome/better_errors/releases)
- [Umweltzone](https://github.com/johnjohndoe/Umweltzone/blob/master/CHANGELOG.md)

**Comment by eyalbe4** [comment]
Thanks for this suggestion @johnjohndoe .
We'll be documenting the plugin's future changes under the releases section on Github.

**Comment by johnjohndoe** [comment]
Recent releases missing notes.

**Comment by johnjohndoe** [comment]
Friendly reminder.

**Comment by eyalbe4** [comment]
Thanks @johnjohndoe!
Our release process automatically saves the release notes on Bintray.
We've just added a Release Notes section in the README, linking to the Release Notes page on Bintray.

**Comment by johnjohndoe** [comment]
Nice, thank you!
